name: Auto Update Icons

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    
    - name: Yarn Upgrader
      uses: browniebroke/yarn-upgrade-action@v1.1
      
    - name: Install dependencies
      run: composer update --no-interaction --no-progress --dev
      
    - name: Compile icons to resources directory
      run: ./vendor/bin/blade-icons-generate

    - name: Create PR for latest version

      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "auto-update: update icons"
        committer: GitHub Action <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        title: "Update icons"
        body: |
            This updates from icons [create-pull-request]
        branch: new-icons-update
