name: Auto Update Icons

on:
  create:
  push:
  pull_request:

permissions:
  contents: write
  pull-requests: write 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2


      
    - name: Create pull request
      uses: shimewtr/submit_pull_request@master
      env:
        GITHUB_ACCESS_TOKEN: ${{secrets.github_token}}



